# Generated by Django 5.2.2 on 2025-06-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('sigla', models.CharField(max_length=4, unique=True, verbose_name='Sigla')),
                ('activo', models.BooleanField(default=False, verbose_name='¿Està activo?')),
                ('piso', models.CharField(blank=True, max_length=5, verbose_name='Piso')),
                ('oficina', models.CharField(blank=True, max_length=10, verbose_name='Oficina Nº')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Áreas de la empresa',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'sigla')},
            },
        ),
    ]
