# Generated by Django 5.2.3 on 2025-06-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['nombre'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Està activo?'),
        ),
    ]
