# Generated by Django 5.2.2 on 2025-06-05 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades de empleado',
                'ordering': ['habilidad'],
                'unique_together': {('habilidad',)},
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=60, verbose_name='Apellido')),
                ('email', models.EmailField(default='empleado@empresa.com', max_length=254)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pais', models.CharField(blank=True, default='No especificado', max_length=100, null=True)),
                ('trabajo', models.CharField(choices=[('0', 'Contador'), ('1', 'Administrativo'), ('2', 'Desarrollador'), ('3', 'Analista funcional'), ('4', 'Otro')], max_length=1, verbose_name='Puesto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento')),
                ('habilidades', models.ManyToManyField(to='empleado.habilidades')),
            ],
            options={
                'verbose_name': 'Mi empleado',
                'verbose_name_plural': 'Empleados de la empresa',
                'ordering': ['-nombre', 'apellido'],
                'unique_together': {('nombre', 'departamento')},
            },
        ),
    ]
