# Generated by Django 5.2.2 on 2025-06-08 23:22

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='observacion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='observacion'),
        ),
    ]
