# Generated by Django 5.2.3 on 2025-06-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleado_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='habilidades',
        ),
    ]
