# Generated by Django 5.2.3 on 2025-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_empleado_habilidades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='habilidades',
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
    ]
